#!/bin/bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/nginx-vhosts/functions"

app="$1"; verify_app_name "$app"

eval "$(config_export global)"
eval "$(config_export app "$app")"

image_tag="$(get_running_image_tag "$app")"
image=$(get_deploying_app_image_name "$app" "$image_tag")

destination=blocklist.temp

copy_from_image "$image" "DOKKU_NGINX_BLOCKLIST" "$destination" 2>/dev/null || true
dokku_log_info1 cat $destination

######## END ########

# CONFIG_FOLDER="$DOKKU_ROOT/$APP/nginx.conf.d"
# CONFIG_FILE="$CONFIG_FOLDER/upload.conf"
# [[ -d "$CONFIG_FOLDER" ]] || mkdir "$CONFIG_FOLDER"

# if  [ -z "$max_upload_size" ]; then
#   dokku_log_info1 "Setting max upload size to 2M"
#   echo "client_max_body_size 2M;" > $CONFIG_FILE
# else
#   dokku_log_info1 "Setting max upload size to $max_upload_size"
#   echo "client_max_body_size $max_upload_size;" > $CONFIG_FILE
# fi

# chown dokku:dokku $CONFIG_FILE

restart_nginx

